# Generated by Django 2.0.4 on 2018-04-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
