# Generated by Django 2.0.4 on 2018-04-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
