# Generated by Django 2.0.4 on 2018-04-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20180421_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='key',
            field=models.CharField(default='00', max_length=100),
        ),
    ]
