# Generated by Django 2.0.4 on 2018-04-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_free_key_premimum_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Free_key',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Premimum_key',
        ),
    ]
